pipeline {
    agent any

    environment {
        IMAGE_NAME = "rajpatel1202/webhook-ci-demo"
        IMAGE_TAG  = "latest"
    }

    stages {

       stage('Build Docker Image') {
    steps {
        sh '''
        echo "Building Docker image from webhook-docker-ci directory"
        docker build -t rajpatel1202/webhook-ci-demo:latest webhook-docker-ci
        '''
    }
}


        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credss',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                docker push $IMAGE_NAME:$IMAGE_TAG
                '''
            }
        }
    }
}
